### ISSUE TITLE
Not compatible with windows 11?

### ISSUE THREAD

**Issue by abouzia** [EugeneSunrise/Invise#1]
![Screenshot 2023-10-30 193732](https://github.com/EugeneSunrise/Invise/assets/2650972/d04d9db9-6e80-4eeb-8f55-73b64635bd9e)

**Comment by EugeneSunrise** [comment]
My bad, I uploaded only arm64 platform in the releases, updated the releases now, try the x64 version, let me know if its ok

**Comment by EugeneSunrise** [comment]
You should also have the .NET 6 Desktop Runtime installed

**Comment by abouzia** [comment]
Works now, thanks.
