### ISSUE TITLE
It doesn't work well

### ISSUE THREAD

**Issue by Allamaris0** [EugeneSunrise/Invise#4]
Fingerprints don't change. There is always the same useragent and WebGL. When I add proxy (with authentication  {protocol}://{username}:{password}@{ip}:{port}), it doesn't work. The saved profile doesn't appear after restart of the app.

But the idea is great and I will be following the project. It would be nice to add noise for canvas and mask webrtc with proxy. And some API for automation with puppeteer/playwritght/selenium.

**Comment by EugeneSunrise** [comment]
> Fingerprints don't change. There is always the same useragent and WebGL. When I add proxy (with authentication  {protocol}://{username}:{password}@{ip}:{port}), it doesn't work. The saved profile doesn't appear after restart of the app.
> 
> 
> 
> But the idea is great and I will be following the project. It would be nice to add noise for canvas and mask webrtc with proxy. And some API for automation with puppeteer/playwritght/selenium.

Hello Dear, 1. Useragent are changeable(you can check last closed) issue. 2. WebGL right now has only one option. 3. What proxy do you use? Right now supports only http/https with auth(check readme). 4. Profiles are saved in the settings.json in program folder, at least everything works for me, I need more information. 5. Using Invise + selenium, playwright or other similar framework just doesn't make much sense, for example, for parsing/scrapping better use cefsharp + angleSharp, not selenium or other shi... also cefsharp does not support selenium or playwright. Puppeteer is possible someday. I think to develop the project towards the possibility of connecting modules to the project (parser module, etc.). Thank you for your feedback❤️
