### ISSUE TITLE
I think you should use core chrome of gologin because it can run offline like chrome/cef

### ISSUE THREAD

**Issue by NCLnclNCL** [EugeneSunrise/Invise#6]
Yeah and i think it is better than cefsharp, its fingerprints  is in preferences file of chrome, random fingerprints or call api to creat file

**Comment by EugeneSunrise** [comment]
By core chrome of gologin do you mean chromedriver?

**Comment by EugeneSunrise** [comment]
> > By core chrome of gologin do you mean chromedriver?
> 
> no, it is a antidetect browser, I mean take their modded chromium version

So you mean to connect with modded chromedriver api? Like Dolphin anty api

**Comment by NCLnclNCL** [comment]
> > > By core chrome of gologin do you mean chromedriver?
> > 
> > 
> > no, it is a antidetect browser, I mean take their modded chromium version
> 
> So you mean to connect with modded chromedriver api? Like Dolphin anty api

no, open direct with start process like chrome like open it with batch file with cmd, có thể tôi cần video để bạn hình dung nó
