### ISSUE TITLE
It doesn't pass Cloudflare challenge

### ISSUE THREAD

**Issue by ares-b** [EugeneSunrise/Invise#7]
Hi,

Great work you've done here. I just tried the Cloudflare challenge and seems like it doesn't pass it.

Tried using https://nowsecure.nl/

**Comment by EugeneSunrise** [comment]
Hello Dear, yes now have some problems with fingerprints and they will be fixed in the next updates, thanks for your feedback❤️

**Comment by loveGhb** [comment]
> Hello Dear, yep, now have some problems with fingerprints and they will be fixed in the next updates, thanks for your feedback❤️

Please tell me what exactly is wrong with them, are they just not right?

**Comment by EugeneSunrise** [comment]
> > Hello Dear, yep, now have some problems with fingerprints and they will be fixed in the next updates, thanks for your feedback❤️
> 
> 
> 
> Please tell me what exactly is wrong with them, are they just not right?

Need to remake the choice of platform (now it is always windows 7) and make changes to the injection of js scripts

**Comment by EugeneSunrise** [comment]
fixed, download last release and test it
