### ISSUE TITLE
Browser close button not working

### ISSUE THREAD

**Issue by cpablast** [EugeneSunrise/Invise#8]
The button to close the browser seems to not be working, the minimize and maximize work. If possible add ability to change WebGL Info and screen resolution.. Also searching at the top bar doesn't work, it only allows searching direct in the search bar

**Comment by EugeneSunrise** [comment]
> The button to close the browser seems to not be working, the minimize and maximize work. If possible add ability to change WebGL Info and screen resolution.. Also searching at the top bar doesn't work, it only allows searching direct in the search bar

Yeah, btnClose need to be fixed :D and ofc i will add webgl & screen res settings, thanks for your feedback❤️

**Comment by cpablast** [comment]
If possible also add a maximize button, I downloaded the source code and will try and several features on my side

**Comment by EugeneSunrise** [comment]
> If possible also add a maximize button, I downloaded the source code and will try and several features on my side

Ok
